/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.app;

import DAO.IDAO_DanhMuc;
import DAO.IDAO_HoaDon;
import entities.DanhMuc;
import entities.HoaDon;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class QL_HoaDon extends javax.swing.JInternalFrame {

    IDAO_DanhMuc iDAO_DanhMuc;
    IDAO_HoaDon iDAO_HoaDon;

    /**
     * Creates new form QL_HoaDon
     */
    public QL_HoaDon() {
        initComponents();
        iDAO_DanhMuc = new IDAO_DanhMuc();
        iDAO_HoaDon = new IDAO_HoaDon();
        loadDanhMuc();
        loadHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_CMND = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        list_TrangThai = new javax.swing.JComboBox<>();
        list_DanhMuc = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Danh sách hóa đơn");
        setInheritsPopupMenu(true);
        setVisible(true);

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Nhân viên", "Mã khách hàng", "Phòng", "Ngày đến", "Ngày đi", "Đặt cọc", "Mã khuyến mại", "Tổng tiền", "Ghi chú", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDon);
        if (tbl_HoaDon.getColumnModel().getColumnCount() > 0) {
            tbl_HoaDon.getColumnModel().getColumn(0).setResizable(false);
            tbl_HoaDon.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbl_HoaDon.getColumnModel().getColumn(1).setPreferredWidth(15);
            tbl_HoaDon.getColumnModel().getColumn(2).setPreferredWidth(25);
            tbl_HoaDon.getColumnModel().getColumn(3).setPreferredWidth(25);
            tbl_HoaDon.getColumnModel().getColumn(4).setPreferredWidth(23);
            tbl_HoaDon.getColumnModel().getColumn(5).setPreferredWidth(25);
            tbl_HoaDon.getColumnModel().getColumn(6).setPreferredWidth(25);
            tbl_HoaDon.getColumnModel().getColumn(7).setPreferredWidth(20);
            tbl_HoaDon.getColumnModel().getColumn(8).setPreferredWidth(20);
            tbl_HoaDon.getColumnModel().getColumn(9).setPreferredWidth(25);
            tbl_HoaDon.getColumnModel().getColumn(10).setPreferredWidth(120);
            tbl_HoaDon.getColumnModel().getColumn(11).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("DANH SÁCH HÓA ĐƠN");

        jLabel2.setText("CMND :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_25px.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        list_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đã thanh toán", "Chưa thanh toán" }));
        list_TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_TrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addComponent(list_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(list_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(txt_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadHoaDon() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_HoaDon.getModel();
        List<HoaDon> listDichVu = iDAO_HoaDon.getAllData();
        defaultTableModel.setRowCount(0);
        int i = 1;
        for (HoaDon hd : listDichVu) {
            defaultTableModel.addRow(new Object[]{i, hd.getMaHoaDon(), hd.getTenNhanVien(), hd.getMaKhachHang(), hd.getTenPhong(), hd.getNgayDen(), hd.getNgayDi(), hd.getDatCoc(), hd.getMaKhuyenMai(), hd.getTongTien(), hd.getGhiChu(), hd.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán"});
            i++;
        }
        tbl_HoaDon.setModel(defaultTableModel);

    }
    private void list_TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_TrangThaiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_list_TrangThaiActionPerformed
    public void locStatus() {
        DefaultComboBoxModel cbb = (DefaultComboBoxModel) list_TrangThai.getModel();
        DefaultTableModel model = (DefaultTableModel) tbl_HoaDon.getModel();
        if (cbb.getElementAt(list_TrangThai.getSelectedIndex()).equals("Tất cả")) {
            List<HoaDon> listDichVu = iDAO_HoaDon.getAllData();
            model.setRowCount(0);
            int i = 1;
            for (HoaDon hd : listDichVu) {
                model.addRow(new Object[]{i, hd.getMaHoaDon(), hd.getTenNhanVien(), hd.getMaKhachHang(), hd.getTenPhong(), hd.getNgayDen(), hd.getNgayDi(), hd.getDatCoc(), hd.getMaKhuyenMai(), hd.getTongTien(), hd.getGhiChu(), hd.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán"});
                i++;
            }
            tbl_HoaDon.setModel(model);
        }else if(cbb.getElementAt(list_TrangThai.getSelectedIndex()).equals("Đã thanh toán")){
            List<HoaDon> listDichVu = iDAO_HoaDon.findDataByStatus(0);
            model.setRowCount(0);
            int i = 1;
            for (HoaDon hd : listDichVu) {
                model.addRow(new Object[]{i, hd.getMaHoaDon(), hd.getTenNhanVien(), hd.getMaKhachHang(), hd.getTenPhong(), hd.getNgayDen(), hd.getNgayDi(), hd.getDatCoc(), hd.getMaKhuyenMai(), hd.getTongTien(), hd.getGhiChu(), hd.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán"});
                i++;
            }
            tbl_HoaDon.setModel(model);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String CMND = txt_CMND.getText();
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_HoaDon.getModel();
        HoaDon hd = iDAO_HoaDon.findDataByCMND(CMND);
        defaultTableModel.setRowCount(0);
        defaultTableModel.addRow(new Object[]{1, hd.getMaHoaDon(), hd.getTenNhanVien(), hd.getMaKhachHang(), hd.getTenPhong(), hd.getNgayDen(), hd.getNgayDi(), hd.getDatCoc(), hd.getMaKhuyenMai(), hd.getTongTien(), hd.getGhiChu(), hd.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán"});
        tbl_HoaDon.setModel(defaultTableModel);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void loadDanhMuc() {
        List<DanhMuc> listDanhMuc = iDAO_DanhMuc.getAllData();
        listDanhMuc.forEach((danhMuc) -> {
            list_DanhMuc.addItem(danhMuc);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<DanhMuc> list_DanhMuc;
    private javax.swing.JComboBox<String> list_TrangThai;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTextField txt_CMND;
    // End of variables declaration//GEN-END:variables

}
