/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.app;

import DAO.IDAO_PhieuDichVu;
import DAO.IDAO_DichVu;
import DAO.IDAO_Phong;
import entities.DichVu;
import entities.PhieuDichVu;
import entities.Phong;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class QL_PhieuDichVu extends javax.swing.JInternalFrame {

    private IDAO_PhieuDichVu dao;
    private IDAO_DichVu dao_dv;
    private IDAO_Phong dao_phong;

    /**
     * Creates new form QL_PhieuDichVu
     */
    public QL_PhieuDichVu() {
        dao = new IDAO_PhieuDichVu();
        dao_dv = new IDAO_DichVu();
        dao_phong = new IDAO_Phong();
        initComponents();
        tbl_PhieuDichVu.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                detail();
            }
        });
        loadPhieuDichVu();
        loadDichVu();
        loadPhong();
    }

    public void loadPhieuDichVu() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_PhieuDichVu.getModel();
        List<PhieuDichVu> data = new ArrayList<>(dao.getAllData());
        defaultTableModel.setRowCount(0);
        data.forEach((pdv) -> {
            defaultTableModel.addRow(new Object[]{pdv.getMaDichVu(), pdv.getTenPhong(),pdv.getGiaDichVu(), pdv.getGhiChu(), pdv.getTrangThai()});
        });
    }

    public void loadDichVu() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_DichVu.getModel();
        List<DichVu> listDichVu = new ArrayList<>(dao_dv.getAllData());
        defaultTableModel.setRowCount(0);
        listDichVu.forEach((dichVu) -> {
            defaultTableModel.addRow(new Object[]{dichVu.getMaDichVu(), dichVu.getTenDichVu(), dichVu.getGiaDichVu(), dichVu.getTrangThai() ? "Phục vụ" : "Không phục vụ"});
        });
    }

    public void loadPhong() {
        List<Phong> data = new ArrayList<>(dao_phong.getAllData());
        DefaultTableModel model = (DefaultTableModel) btl_Phong.getModel();
        model.setRowCount(0);
        data.forEach((p) -> {
            model.addRow(new Object[]{p.getMaPhong(), p.getTenPhong(), p.getTenDanhMuc(), p.getSoGiuong(), p.getGhiChu(), p.getTrangThai() ? "Còn trống" : "Đã đặt"});
        });
        btl_Phong.setModel(model);
    }

    public void clear() {
        txt_maDichVu.setText("");
        txt_maPhong.setText("");
        txt_ghiChu.setText("");

    }

    public void detail() {
        int SelectedRow = tbl_PhieuDichVu.getSelectedRow();
        if (SelectedRow >= 0) {
            int id = (int) tbl_PhieuDichVu.getValueAt(SelectedRow, 0);
            PhieuDichVu pdv = dao.findDataById(id);
            txt_maDichVu.setText(pdv.getMaDichVu()+"");
            txt_maPhong.setText(pdv.getMaPhong()+"");
            txt_ghiChu.setText(pdv.getGhiChu());
            if (pdv.getTrangThai() == false) {
                check_khongHoatDong.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DichVu = new javax.swing.JTable();
        btn_DichVuTimKiem = new javax.swing.JToggleButton();
        txt_DichVuTimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_PhongTimKiem = new javax.swing.JTextField();
        btn_PhongTimKiem = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        btl_Phong = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_PhieuDichVu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_maDichVu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_maPhong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        check_hoatDong = new javax.swing.JRadioButton();
        check_khongHoatDong = new javax.swing.JRadioButton();
        add_PhieuDichVu = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Quản lý phiếu dịch vụ");
        setAutoscrolls(true);
        setInheritsPopupMenu(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tbl_DichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá dịch vụ", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tbl_DichVu);
        if (tbl_DichVu.getColumnModel().getColumnCount() > 0) {
            tbl_DichVu.getColumnModel().getColumn(3).setHeaderValue("Trạng thái");
        }

        btn_DichVuTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_DichVuTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_25px.png"))); // NOI18N
        btn_DichVuTimKiem.setText("Tìm kiếm");
        btn_DichVuTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DichVuTimKiemActionPerformed(evt);
            }
        });

        txt_DichVuTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nhập dịch vụ tìm kiếm:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nhập phòng tìm kiếm:");

        txt_PhongTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_PhongTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_PhongTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_25px.png"))); // NOI18N
        btn_PhongTimKiem.setText("Tìm kiếm");
        btn_PhongTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhongTimKiemActionPerformed(evt);
            }
        });

        btl_Phong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tên phòng (số phòng)", "Loại phòng", "Số giường", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(btl_Phong);
        if (btl_Phong.getColumnModel().getColumnCount() > 0) {
            btl_Phong.getColumnModel().getColumn(3).setHeaderValue("Trạng thái");
        }

        tbl_PhieuDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên phòng (số phòng)", "Giá dịch vụ", "Ghi chú", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_PhieuDichVu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(txt_PhongTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_PhongTimKiem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_DichVuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_DichVuTimKiem)))
                        .addContainerGap(481, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DichVuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DichVuTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PhongTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_PhongTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PHIẾU DỊCH VỤ");

        jLabel5.setText("Mã dịch vụ:");

        jLabel6.setText("Tên phòng:");

        jLabel8.setText("Ghi chú:");

        jLabel9.setText("Trạng thái:");

        check_hoatDong.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(check_hoatDong);
        check_hoatDong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        check_hoatDong.setForeground(new java.awt.Color(0, 0, 204));
        check_hoatDong.setSelected(true);
        check_hoatDong.setText("Hoạt động");
        check_hoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_hoatDongActionPerformed(evt);
            }
        });

        check_khongHoatDong.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(check_khongHoatDong);
        check_khongHoatDong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        check_khongHoatDong.setForeground(new java.awt.Color(255, 51, 51));
        check_khongHoatDong.setText("Không hoạt động");

        add_PhieuDichVu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_PhieuDichVu.setForeground(new java.awt.Color(51, 0, 204));
        add_PhieuDichVu.setText("THÊM DỊCH VỤ");
        add_PhieuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_PhieuDichVuActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_25px.png"))); // NOI18N
        jButton3.setText("Tìm kiếm");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/broom_25px.png"))); // NOI18N
        jButton4.setText("Clear");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete_25px.png"))); // NOI18N
        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane4.setViewportView(txt_ghiChu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_maDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(check_hoatDong)
                        .addGap(84, 84, 84)
                        .addComponent(check_khongHoatDong))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add_PhieuDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_maDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8)))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(check_hoatDong)
                    .addComponent(check_khongHoatDong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_PhieuDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DichVuTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DichVuTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DichVuTimKiemActionPerformed

    private void btn_PhongTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhongTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PhongTimKiemActionPerformed

    private void check_hoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_hoatDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_hoatDongActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int id = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa không?", "Xác nhận xóa!", JOptionPane.OK_CANCEL_OPTION);
        if (id == JOptionPane.OK_OPTION) {
            PhieuDichVu pdv = new PhieuDichVu();
            int idDichVu = Integer.parseInt(txt_maDichVu.getText());
            dao.deleteData(idDichVu);
            clear();
            loadPhieuDichVu();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void add_PhieuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_PhieuDichVuActionPerformed
        // TODO add your handling code here:
        PhieuDichVu pdv = new PhieuDichVu();
        pdv.setMaDichVu(Integer.parseInt(txt_maDichVu.getText()));
        pdv.setMaPhong(Integer.parseInt(txt_maPhong.getText()));
        pdv.setGhiChu(txt_ghiChu.getText());
        pdv.setTrangThai(check_hoatDong.isSelected());
        dao.insertData(pdv);
        loadPhieuDichVu();
        clear();
    }//GEN-LAST:event_add_PhieuDichVuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_PhieuDichVu;
    private javax.swing.JTable btl_Phong;
    private javax.swing.JToggleButton btn_DichVuTimKiem;
    private javax.swing.JToggleButton btn_PhongTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton check_hoatDong;
    private javax.swing.JRadioButton check_khongHoatDong;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_DichVu;
    private javax.swing.JTable tbl_PhieuDichVu;
    private javax.swing.JTextField txt_DichVuTimKiem;
    private javax.swing.JTextField txt_PhongTimKiem;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_maDichVu;
    private javax.swing.JTextField txt_maPhong;
    // End of variables declaration//GEN-END:variables
}
