/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.app;

import DAO.IDAO_DanhMuc;
import DAO.IDAO_KhuyenMai;
import DAO.IDAO_NhanVien;
import entities.DanhMuc;
import entities.KhuyenMai;
import entities.NhanVien;
import java.util.List;

/**
 *
 * @author dell
 */
public class QL_DatPhong extends javax.swing.JInternalFrame {

    private final IDAO_DanhMuc iDAO_DanhMuc;
    private final IDAO_KhuyenMai iDAO_KhuyenMai;
    private final IDAO_NhanVien iDAO_NhanVien;

    public QL_DatPhong() {
        initComponents();
        iDAO_DanhMuc = new IDAO_DanhMuc();
        iDAO_KhuyenMai = new IDAO_KhuyenMai();
        iDAO_NhanVien = new IDAO_NhanVien();
        loadDanhMuc();
        loadKhuyenMai();
        loadNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        txt_DatCoc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_MaHoaDon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        list_KhuyenMai = new javax.swing.JComboBox<>();
        list_MaNhanVien = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_MaKhachHang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        check_ThanhToan = new javax.swing.JRadioButton();
        check_ChuaThanhToan = new javax.swing.JRadioButton();
        btn_ThanhToan = new javax.swing.JToggleButton();
        btn_CapNhat = new javax.swing.JToggleButton();
        btn_HuyPhong = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JLabel();
        btn_Clear = new javax.swing.JToggleButton();
        txt_TongTien1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_MaPhong = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        date_NgayDen = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        date_NgayDi = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txt_MaKhachHangTimKiem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_TimKiemDonHang = new javax.swing.JToggleButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_DichVu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_TenKhachHangTimKiem = new javax.swing.JTextField();
        btn_TimKiemTen = new javax.swing.JToggleButton();
        btn_TaoKhachHangMoi = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Phong = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        list_DanhMuc = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_KhachHang = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_DichVu1 = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Đặt Phòng");
        setAutoscrolls(true);
        setRequestFocusEnabled(false);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel5.setText("Đặt cọc:");

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane1.setViewportView(txt_GhiChu);

        txt_DatCoc.setText("0");

        jLabel1.setText("Mã hóa đơn: ");

        txt_MaHoaDon.setEditable(false);

        jLabel7.setText("Khuyến mại: ");

        jLabel3.setText("Mã nhân viên:");

        jLabel4.setText("Mã khách hàng:");

        jLabel8.setText("Ghi chú:");

        jLabel9.setText("Trạng thái:");

        check_ThanhToan.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(check_ThanhToan);
        check_ThanhToan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        check_ThanhToan.setForeground(new java.awt.Color(0, 0, 204));
        check_ThanhToan.setText("Đã thanh toán");
        check_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_ThanhToanActionPerformed(evt);
            }
        });

        check_ChuaThanhToan.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(check_ChuaThanhToan);
        check_ChuaThanhToan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        check_ChuaThanhToan.setForeground(new java.awt.Color(255, 0, 51));
        check_ChuaThanhToan.setSelected(true);
        check_ChuaThanhToan.setText("Chưa thanh toán");

        btn_ThanhToan.setBackground(new java.awt.Color(0, 204, 0));
        btn_ThanhToan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(0, 0, 102));
        btn_ThanhToan.setText("Thanh toán");
        btn_ThanhToan.setOpaque(true);
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        btn_CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update_25px.png"))); // NOI18N
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        btn_HuyPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete_25px.png"))); // NOI18N
        btn_HuyPhong.setText("Hủy phòng");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel2.setText("HÓA ĐƠN ĐẶT PHÒNG");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel6.setText("Tổng tiền:");

        txt_TongTien.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        txt_TongTien.setForeground(new java.awt.Color(255, 51, 51));
        txt_TongTien.setText("0");

        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/broom_25px.png"))); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        txt_TongTien1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        txt_TongTien1.setForeground(new java.awt.Color(255, 51, 51));
        txt_TongTien1.setText("VNĐ");

        jLabel12.setText("Mã Phòng:");

        jLabel16.setText("Ngày đến:");

        jLabel17.setText("Ngày đi:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Thêm dịch vụ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_TongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(list_KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_DatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_MaHoaDon)
                                    .addComponent(list_MaNhanVien, 0, 269, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_MaKhachHang)
                                    .addComponent(txt_MaPhong)
                                    .addComponent(date_NgayDen, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(date_NgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(check_ThanhToan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(check_ChuaThanhToan))
                                    .addComponent(jScrollPane1)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_HuyPhong)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(list_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_MaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(date_NgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_DatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(list_KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(check_ChuaThanhToan)
                        .addComponent(check_ThanhToan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TongTien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhat)
                    .addComponent(btn_Clear)
                    .addComponent(btn_HuyPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        txt_MaKhachHangTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/filter_25px.png"))); // NOI18N
        jLabel15.setText("Trạng thái:");

        btn_TimKiemDonHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TimKiemDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_25px.png"))); // NOI18N
        btn_TimKiemDonHang.setText("Tìm kiếm");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đã thanh toán", "Chưa thanh toán" }));

        tbl_DichVu.setBackground(new java.awt.Color(204, 255, 255));
        tbl_DichVu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbl_DichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Mã phòng", "Ghi chú", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DichVu.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(tbl_DichVu);
        if (tbl_DichVu.getColumnModel().getColumnCount() > 0) {
            tbl_DichVu.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_DichVu.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbl_DichVu.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbl_DichVu.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm..."));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/team_25px.png"))); // NOI18N
        jLabel13.setText("CMND hoặc Số điện thoại khách hàng:");

        txt_TenKhachHangTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_TimKiemTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TimKiemTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_25px.png"))); // NOI18N
        btn_TimKiemTen.setText("Tìm kiếm");

        btn_TaoKhachHangMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TaoKhachHangMoi.setForeground(new java.awt.Color(0, 0, 153));
        btn_TaoKhachHangMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_25px.png"))); // NOI18N
        btn_TaoKhachHangMoi.setText("Tạo mới");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txt_TenKhachHangTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TimKiemTen)
                .addGap(18, 18, 18)
                .addComponent(btn_TaoKhachHangMoi)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenKhachHangTimKiem)
                    .addComponent(jLabel13)
                    .addComponent(btn_TimKiemTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TaoKhachHangMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbl_Phong.setBackground(new java.awt.Color(102, 255, 255));
        tbl_Phong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        tbl_Phong.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbl_Phong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tên phòng (số phòng)", "Loại phòng", "Giá phòng", "Ghi chú", "Khuyến mại", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Phong.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tbl_Phong);
        if (tbl_Phong.getColumnModel().getColumnCount() > 0) {
            tbl_Phong.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_Phong.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbl_Phong.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbl_Phong.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbl_Phong.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbl_Phong.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/filter_25px.png"))); // NOI18N
        jLabel14.setText("Mã khách hàng:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/filter_25px.png"))); // NOI18N
        jLabel10.setText("Trạng thái:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chưa đặt", "Đã đặt" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/filter_25px.png"))); // NOI18N
        jLabel11.setText("Hạng phòng:");

        list_DanhMuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tbl_KhachHang.setBackground(new java.awt.Color(204, 255, 255));
        tbl_KhachHang.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbl_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "CMND", "Ghi chú", "Số lượt", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_KhachHang.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tbl_KhachHang);
        if (tbl_KhachHang.getColumnModel().getColumnCount() > 0) {
            tbl_KhachHang.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_KhachHang.getColumnModel().getColumn(1).setPreferredWidth(43);
            tbl_KhachHang.getColumnModel().getColumn(2).setPreferredWidth(40);
            tbl_KhachHang.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbl_KhachHang.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbl_KhachHang.getColumnModel().getColumn(5).setPreferredWidth(20);
            tbl_KhachHang.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        tbl_DichVu1.setBackground(new java.awt.Color(204, 255, 255));
        tbl_DichVu1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tbl_DichVu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã danh mục", "Mã thiết bị", "Số lượng", "Ghi chú", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DichVu1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(tbl_DichVu1);
        if (tbl_DichVu1.getColumnModel().getColumnCount() > 0) {
            tbl_DichVu1.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_DichVu1.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbl_DichVu1.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbl_DichVu1.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbl_DichVu1.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(list_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_MaKhachHangTimKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_TimKiemDonHang)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(list_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_MaKhachHangTimKiem)
                            .addComponent(btn_TimKiemDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDanhMuc() {
        List<DanhMuc> listDanhMuc = iDAO_DanhMuc.getAllData();
        listDanhMuc.forEach((DanhMuc danhMuc) -> {
            list_DanhMuc.addItem(danhMuc);
        });
    }

    private void loadKhuyenMai() {
        List<KhuyenMai> listKhuyenMai = iDAO_KhuyenMai.getAllData();
        listKhuyenMai.forEach((khuyenMai) -> {
            list_KhuyenMai.addItem(khuyenMai);
        });
    }

    private void loadNhanVien() {
        List<NhanVien> listNhanVien = iDAO_NhanVien.getAllData();
        listNhanVien.forEach((nhanVien) -> {
            list_MaNhanVien.addItem(nhanVien);
        });
    }
    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void check_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_ThanhToanActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_CapNhat;
    private javax.swing.JToggleButton btn_Clear;
    private javax.swing.JToggleButton btn_HuyPhong;
    private javax.swing.JToggleButton btn_TaoKhachHangMoi;
    private javax.swing.JToggleButton btn_ThanhToan;
    private javax.swing.JToggleButton btn_TimKiemDonHang;
    private javax.swing.JToggleButton btn_TimKiemTen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton check_ChuaThanhToan;
    private javax.swing.JRadioButton check_ThanhToan;
    private com.toedter.calendar.JDateChooser date_NgayDen;
    private com.toedter.calendar.JDateChooser date_NgayDi;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<DanhMuc> list_DanhMuc;
    private javax.swing.JComboBox<KhuyenMai> list_KhuyenMai;
    private javax.swing.JComboBox<NhanVien> list_MaNhanVien;
    private javax.swing.JTable tbl_DichVu;
    private javax.swing.JTable tbl_DichVu1;
    private javax.swing.JTable tbl_KhachHang;
    private javax.swing.JTable tbl_Phong;
    private javax.swing.JTextField txt_DatCoc;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_MaHoaDon;
    private javax.swing.JTextField txt_MaKhachHang;
    private javax.swing.JTextField txt_MaKhachHangTimKiem;
    private javax.swing.JTextField txt_MaPhong;
    private javax.swing.JTextField txt_TenKhachHangTimKiem;
    private javax.swing.JLabel txt_TongTien;
    private javax.swing.JLabel txt_TongTien1;
    // End of variables declaration//GEN-END:variables

}
