package main.app;

import DAO.IDAO_KhuyenMai;
import entities.KhuyenMai;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class QL_KhuyenMai extends javax.swing.JInternalFrame {

    /**
     * Creates new form QL_KhuyenMai
     */
    private final IDAO_KhuyenMai iDAO_KhuyenMai;
    private boolean edit = false;

    public QL_KhuyenMai() {
        initComponents();
        iDAO_KhuyenMai = new IDAO_KhuyenMai();
        load_KhuyenMai();
        tbl_QuanLyKhuyenMai.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            details_KhuyenMai();
        });
 btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_25px.png"))); // NOI18N
        btn_Sua.setText("Thêm mới");
    }

    private void load_KhuyenMai() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_QuanLyKhuyenMai.getModel();
        List<KhuyenMai> listKhuyenMai = new ArrayList<>(iDAO_KhuyenMai.getAllData());
        defaultTableModel.setRowCount(0);
        listKhuyenMai.stream().forEach((km) -> {
            defaultTableModel.addRow(new Object[]{km.getMaKhuyenMai(), km.getTenKhuyenMai(), km.getNoiDung(), km.getGiaTri(), km.getTrangThai() ? "Phục vụ" : "Không phục vụ"});
        });
    
    }

    private void clear() {
        txt_GiaTri.setText("0");
        txt_MaKhuyenMai.setText(null);
        txt_NoiDung.setText(null);
        txt_TenKhuyenMai.setText(null);
        check_PhucVu.setSelected(true);
        check_KhongPhucVu.setSelected(false);
        edit = false;
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_25px.png"))); // NOI18N
        btn_Sua.setText("Thêm mới");
    }

    private void details_KhuyenMai() {
        int selectedRow = tbl_QuanLyKhuyenMai.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (int) tbl_QuanLyKhuyenMai.getValueAt(selectedRow, 0);
            KhuyenMai khuyenMai = iDAO_KhuyenMai.findDataById(id);
            txt_GiaTri.setText(khuyenMai.getGiaTri() + "");

            txt_MaKhuyenMai.setText(khuyenMai.getMaKhuyenMai() + "");
            txt_NoiDung.setText(khuyenMai.getNoiDung() + "");
            txt_TenKhuyenMai.setText(khuyenMai.getTenKhuyenMai() + "");
            check_PhucVu.setSelected(true);
            if (khuyenMai.getTrangThai() == false) {
                check_KhongPhucVu.setSelected(true);
            }
            edit = true;
        }
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update_25px.png"))); // NOI18N
        btn_Sua.setText("Cập nhật");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaKhuyenMai = new javax.swing.JTextField();
        txt_TenKhuyenMai = new javax.swing.JTextField();
        txt_GiaTri = new javax.swing.JTextField();
        check_PhucVu = new javax.swing.JRadioButton();
        check_KhongPhucVu = new javax.swing.JRadioButton();
        btn_TimKiem = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_NoiDung = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_QuanLyKhuyenMai = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Quản lý khuyến mãi");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Mã khuyến mãi:");

        jLabel2.setText("Tên khuyến mãi:");

        jLabel3.setText("Nội dung:");

        jLabel4.setText("Giá trị:");

        jLabel6.setText("Trạng thái:");

        txt_MaKhuyenMai.setEnabled(false);
        txt_MaKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaKhuyenMaiActionPerformed(evt);
            }
        });

        txt_TenKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenKhuyenMaiActionPerformed(evt);
            }
        });

        txt_GiaTri.setText("0");
        txt_GiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaTriActionPerformed(evt);
            }
        });

        buttonGroup1.add(check_PhucVu);
        check_PhucVu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        check_PhucVu.setForeground(new java.awt.Color(0, 0, 255));
        check_PhucVu.setSelected(true);
        check_PhucVu.setText("Phục vụ");
        check_PhucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_PhucVuActionPerformed(evt);
            }
        });

        buttonGroup1.add(check_KhongPhucVu);
        check_KhongPhucVu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        check_KhongPhucVu.setForeground(new java.awt.Color(255, 0, 0));
        check_KhongPhucVu.setText("Không phục vụ");

        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_25px.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete_25px.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setPreferredSize(new java.awt.Dimension(95, 33));
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(0, 102, 102));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update_25px.png"))); // NOI18N
        btn_Sua.setText("Cập nhật");
        btn_Sua.setPreferredSize(new java.awt.Dimension(95, 33));
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/broom_25px.png"))); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.setPreferredSize(new java.awt.Dimension(95, 33));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        txt_NoiDung.setColumns(20);
        txt_NoiDung.setRows(5);
        jScrollPane2.setViewportView(txt_NoiDung);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txt_TenKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(check_PhucVu)
                                        .addGap(18, 18, 18)
                                        .addComponent(check_KhongPhucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(btn_TimKiem))))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_TenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(check_PhucVu)
                    .addComponent(check_KhongPhucVu))
                .addGap(46, 46, 46)
                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem))
                .addGap(21, 21, 21))
        );

        tbl_QuanLyKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Nội dung", "Giá trị", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_QuanLyKhuyenMai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaKhuyenMaiActionPerformed

    private void txt_TenKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenKhuyenMaiActionPerformed

    private void txt_GiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaTriActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        String stringTimKiem = JOptionPane.showInputDialog(this, "Nhập vào tên khuyến mại để tìm kiếm:", "Tìm kiếm", JOptionPane.QUESTION_MESSAGE);
        List<KhuyenMai> listKhuyenMai = iDAO_KhuyenMai.findDataByName(stringTimKiem);
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_QuanLyKhuyenMai.getModel();
        defaultTableModel.setRowCount(0);
        listKhuyenMai.stream().forEach((km) -> {
            defaultTableModel.addRow(new Object[]{km.getMaKhuyenMai(), km.getTenKhuyenMai(), km.getNoiDung(), km.getGiaTri(), km.getTrangThai() ? "Phục vụ" : "Không phục vụ"});
        });
        clear();
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void check_PhucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_PhucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_PhucVuActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        KhuyenMai khuyenMai = new KhuyenMai();
        khuyenMai.setGiaTri(Float.parseFloat(txt_GiaTri.getText()));
        khuyenMai.setNoiDung(txt_NoiDung.getText());
        khuyenMai.setTenKhuyenMai(txt_TenKhuyenMai.getText());
        khuyenMai.setTrangThai(check_PhucVu.isSelected());
        if (edit == true) {
            khuyenMai.setMaKhuyenMai(Integer.parseInt(txt_MaKhuyenMai.getText()));
            iDAO_KhuyenMai.updateData(khuyenMai);
            edit = false;
        } else {
            iDAO_KhuyenMai.insertData(khuyenMai);
            edit = false;
        }
        load_KhuyenMai();
        clear();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clear();
        
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int selectedRow = tbl_QuanLyKhuyenMai.getSelectedRow();
        int idDelete = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa không?", "Xác nhận xóa!", JOptionPane.OK_CANCEL_OPTION);
        if (idDelete == JOptionPane.OK_OPTION) {
            idDelete = (int) tbl_QuanLyKhuyenMai.getValueAt(selectedRow, 0);
            iDAO_KhuyenMai.deleteData(idDelete);
            load_KhuyenMai();
            clear();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton check_KhongPhucVu;
    private javax.swing.JRadioButton check_PhucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_QuanLyKhuyenMai;
    private javax.swing.JTextField txt_GiaTri;
    private javax.swing.JTextField txt_MaKhuyenMai;
    private javax.swing.JTextArea txt_NoiDung;
    private javax.swing.JTextField txt_TenKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
